// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: shared/proto/authorization/authorization.proto

package authorization

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Check Permission
type CheckPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Resource      string                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionRequest) Reset() {
	*x = CheckPermissionRequest{}
	mi := &file_shared_proto_authorization_authorization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionRequest) ProtoMessage() {}

func (x *CheckPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_authorization_authorization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionRequest.ProtoReflect.Descriptor instead.
func (*CheckPermissionRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_authorization_authorization_proto_rawDescGZIP(), []int{0}
}

func (x *CheckPermissionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckPermissionRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *CheckPermissionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type CheckPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionResponse) Reset() {
	*x = CheckPermissionResponse{}
	mi := &file_shared_proto_authorization_authorization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionResponse) ProtoMessage() {}

func (x *CheckPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_authorization_authorization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionResponse.ProtoReflect.Descriptor instead.
func (*CheckPermissionResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_authorization_authorization_proto_rawDescGZIP(), []int{1}
}

func (x *CheckPermissionResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckPermissionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Get User Permissions
type GetUserPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPermissionsRequest) Reset() {
	*x = GetUserPermissionsRequest{}
	mi := &file_shared_proto_authorization_authorization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPermissionsRequest) ProtoMessage() {}

func (x *GetUserPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_authorization_authorization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPermissionsRequest.ProtoReflect.Descriptor instead.
func (*GetUserPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_authorization_authorization_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserPermissionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserPermissionsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PermissionNames []string               `protobuf:"bytes,1,rep,name=permission_names,json=permissionNames,proto3" json:"permission_names,omitempty"`
	Success         bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetUserPermissionsResponse) Reset() {
	*x = GetUserPermissionsResponse{}
	mi := &file_shared_proto_authorization_authorization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPermissionsResponse) ProtoMessage() {}

func (x *GetUserPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_authorization_authorization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPermissionsResponse.ProtoReflect.Descriptor instead.
func (*GetUserPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_authorization_authorization_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserPermissionsResponse) GetPermissionNames() []string {
	if x != nil {
		return x.PermissionNames
	}
	return nil
}

func (x *GetUserPermissionsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Validate Access
type ValidateAccessRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UserId              string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RequiredPermissions []string               `protobuf:"bytes,2,rep,name=required_permissions,json=requiredPermissions,proto3" json:"required_permissions,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ValidateAccessRequest) Reset() {
	*x = ValidateAccessRequest{}
	mi := &file_shared_proto_authorization_authorization_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAccessRequest) ProtoMessage() {}

func (x *ValidateAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_authorization_authorization_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAccessRequest.ProtoReflect.Descriptor instead.
func (*ValidateAccessRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_authorization_authorization_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateAccessRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateAccessRequest) GetRequiredPermissions() []string {
	if x != nil {
		return x.RequiredPermissions
	}
	return nil
}

type ValidateAccessResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Authorized         bool                   `protobuf:"varint,1,opt,name=authorized,proto3" json:"authorized,omitempty"`
	MissingPermissions []string               `protobuf:"bytes,2,rep,name=missing_permissions,json=missingPermissions,proto3" json:"missing_permissions,omitempty"`
	Message            string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ValidateAccessResponse) Reset() {
	*x = ValidateAccessResponse{}
	mi := &file_shared_proto_authorization_authorization_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAccessResponse) ProtoMessage() {}

func (x *ValidateAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_authorization_authorization_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAccessResponse.ProtoReflect.Descriptor instead.
func (*ValidateAccessResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_authorization_authorization_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateAccessResponse) GetAuthorized() bool {
	if x != nil {
		return x.Authorized
	}
	return false
}

func (x *ValidateAccessResponse) GetMissingPermissions() []string {
	if x != nil {
		return x.MissingPermissions
	}
	return nil
}

func (x *ValidateAccessResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_shared_proto_authorization_authorization_proto protoreflect.FileDescriptor

const file_shared_proto_authorization_authorization_proto_rawDesc = "" +
	"\n" +
	".shared/proto/authorization/authorization.proto\x12\rauthorization\"e\n" +
	"\x16CheckPermissionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"M\n" +
	"\x17CheckPermissionResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"4\n" +
	"\x19GetUserPermissionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"a\n" +
	"\x1aGetUserPermissionsResponse\x12)\n" +
	"\x10permission_names\x18\x01 \x03(\tR\x0fpermissionNames\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"c\n" +
	"\x15ValidateAccessRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x121\n" +
	"\x14required_permissions\x18\x02 \x03(\tR\x13requiredPermissions\"\x83\x01\n" +
	"\x16ValidateAccessResponse\x12\x1e\n" +
	"\n" +
	"authorized\x18\x01 \x01(\bR\n" +
	"authorized\x12/\n" +
	"\x13missing_permissions\x18\x02 \x03(\tR\x12missingPermissions\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xc2\x02\n" +
	"\x14AuthorizationService\x12`\n" +
	"\x0fCheckPermission\x12%.authorization.CheckPermissionRequest\x1a&.authorization.CheckPermissionResponse\x12i\n" +
	"\x12GetUserPermissions\x12(.authorization.GetUserPermissionsRequest\x1a).authorization.GetUserPermissionsResponse\x12]\n" +
	"\x0eValidateAccess\x12$.authorization.ValidateAccessRequest\x1a%.authorization.ValidateAccessResponseB%Z#engine/internal/proto/authorizationb\x06proto3"

var (
	file_shared_proto_authorization_authorization_proto_rawDescOnce sync.Once
	file_shared_proto_authorization_authorization_proto_rawDescData []byte
)

func file_shared_proto_authorization_authorization_proto_rawDescGZIP() []byte {
	file_shared_proto_authorization_authorization_proto_rawDescOnce.Do(func() {
		file_shared_proto_authorization_authorization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_authorization_authorization_proto_rawDesc), len(file_shared_proto_authorization_authorization_proto_rawDesc)))
	})
	return file_shared_proto_authorization_authorization_proto_rawDescData
}

var file_shared_proto_authorization_authorization_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_shared_proto_authorization_authorization_proto_goTypes = []any{
	(*CheckPermissionRequest)(nil),     // 0: authorization.CheckPermissionRequest
	(*CheckPermissionResponse)(nil),    // 1: authorization.CheckPermissionResponse
	(*GetUserPermissionsRequest)(nil),  // 2: authorization.GetUserPermissionsRequest
	(*GetUserPermissionsResponse)(nil), // 3: authorization.GetUserPermissionsResponse
	(*ValidateAccessRequest)(nil),      // 4: authorization.ValidateAccessRequest
	(*ValidateAccessResponse)(nil),     // 5: authorization.ValidateAccessResponse
}
var file_shared_proto_authorization_authorization_proto_depIdxs = []int32{
	0, // 0: authorization.AuthorizationService.CheckPermission:input_type -> authorization.CheckPermissionRequest
	2, // 1: authorization.AuthorizationService.GetUserPermissions:input_type -> authorization.GetUserPermissionsRequest
	4, // 2: authorization.AuthorizationService.ValidateAccess:input_type -> authorization.ValidateAccessRequest
	1, // 3: authorization.AuthorizationService.CheckPermission:output_type -> authorization.CheckPermissionResponse
	3, // 4: authorization.AuthorizationService.GetUserPermissions:output_type -> authorization.GetUserPermissionsResponse
	5, // 5: authorization.AuthorizationService.ValidateAccess:output_type -> authorization.ValidateAccessResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shared_proto_authorization_authorization_proto_init() }
func file_shared_proto_authorization_authorization_proto_init() {
	if File_shared_proto_authorization_authorization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_authorization_authorization_proto_rawDesc), len(file_shared_proto_authorization_authorization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_authorization_authorization_proto_goTypes,
		DependencyIndexes: file_shared_proto_authorization_authorization_proto_depIdxs,
		MessageInfos:      file_shared_proto_authorization_authorization_proto_msgTypes,
	}.Build()
	File_shared_proto_authorization_authorization_proto = out.File
	file_shared_proto_authorization_authorization_proto_goTypes = nil
	file_shared_proto_authorization_authorization_proto_depIdxs = nil
}
